server:
  port: 8082
spring:
  application:
    name: revelation-realtime
  cloud:
    discovery:
      client:
        simple:
          instances:
            revelation-realtime[0]:
              uri: http://localhost:${wiremock.server.port}
eureka:
  client:
    enabled: false
